name: Fetch latest data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '35 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - uses: hubgit/curl-etag@master
      with:
        args: original/countries_v1.geojson https://c19pub.azureedge.net/assets/geo/countries_v1.geojson
    - uses: hubgit/curl-etag@master
      with:
        args: original/countries_latest.geojson https://c19downloads.azureedge.net/downloads/data/countries_latest.json
    - uses: hubgit/curl-etag@master
      with:
        args: original/population.geojson https://c19pub.azureedge.net/assets/population/population.json
    - name: Process data
      run: scripts/process.sh
    - name: Commit and push if it changed
      run: scripts/commit.sh
