name: Fetch latest data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: scripts/update.sh
    - name: Commit and push if it changed
      run: scripts/commit.sh
